### ISSUE TITLE
JetBrains: No Prompt is shown when hovering over the button

### ISSUE THREAD

**Issue by RajatNagoria** [sourcegraph/jetbrains#2081]
### IDE Information

PyCharm 2024.1.4 (Community Edition)
Build #PC-233.13763.11, built on January 26, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
com.sourcegraph.jetbrains (6.0.30)

### Bug Description

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your PyCharm editor
2. Login to Cody with any user
3. Navigate to chat section & hover over anu button

### Observed behavior:
No Prompt is shown when hovering over the button

### Expected behavior:
Prompt should be shown when hover over button

### Additional context

**Video link:** https://drive.google.com/file/d/1u44MVT58luR2q908VRIxRcs6WyV6XmVr/view

**Comment by mkondratek** [comment]
Copy and Apply contain the texts. The other two show the tooltip on hover. Possibly it got fixed in the meantime.

<img width="354" alt="image" src="https://github.com/user-attachments/assets/95fa7608-1e7a-4903-9ae4-0bd31f6cb355">

closing

**Comment by taylorsperry** [comment]
@mkondratek I still don't see the hover text for insert / save to new file in JB. I'm wondering if that's because VSC is now showing this (instead of the icons): 
<img width="560" alt="Screenshot 2024-09-04 at 2 20 18 PM" src="https://github.com/user-attachments/assets/faddf7f4-294b-4814-959b-5698de40a721">
