### ISSUE TITLE
bug: Accessing Commands using right-click dropdown menu does not pass in highlighted code

### ISSUE THREAD

**Issue by morgangauth** [sourcegraph/jetbrains#232]
### Installation Information

IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Cody v5.2.12694

### Describe the bug

1. Highlight a snippet of code
2. Right-click the highlighted area, and click Cody>Generate Docstring 
<img width="529" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/113058716/29098b17-fbe5-4415-97ee-1fa033032671">

3. Observe that Cody will claim : `There is no code provided to generate documentation for.` 
<img width="452" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/113058716/8b362265-c211-41e9-87e3-7dc6b6f5d6a3">

4. With the same code snippet highlighted, go to the Commands tab 
<img width="454" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/113058716/8b005d17-3578-4db0-be08-c124ad7f8a98">

5. Observe that the docstring is generated as expected
<img width="455" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/113058716/a168ffe3-35ee-45cb-8edb-0b5e548c0f8d">

### Expected behavior

Highlighted text should be passed into Cody when accessing the right-click Commands options, i.e. step 3 above should match step 5.

### Additional context (logs, images, etc)

https://www.loom.com/share/6ba61df830ab41ae9da3f14d30f05f04

**Comment by mkondratek** [comment]
Thanks for the detailed description! 💟 

I quickly tested this on our recent WIP changes related to the new chat UI - it seems that it fixes the problem.

**Comment by taylorsperry** [comment]
Yep, looks like this is fixed.

**Comment by morgangauth** [comment]
@taylorsperry This is still occurring on v5.2.17749. Can we reopen this issue?

**Comment by morgangauth** [comment]
@taylorsperry This is still occurring on v5.2.17749. Can we reopen this issue?


https://github.com/sourcegraph/jetbrains/assets/113058716/89f112f0-eb0c-4cc1-847d-41f17899b44e

**Comment by taylorsperry** [comment]
I'm seeing the same issue (when I trigger the doc command with the right-click menu, Cody says there is no code provided), but I'm not getting the same description that @morgangauth is seeing after the code snippet, which is also a problem; for me it's just blank. [Loom](https://www.loom.com/share/44a2452f1a85470091ba6bbeb685f0b5?sid=476f3bc5-0fb4-4341-b5b9-3cad3f0e89ed).

**Comment by mkondratek** [comment]
It's fixed, but it's not yet released.

**Comment by morgangauth** [comment]
As of v5.2.18630, it seems this issue still exists. The **first** right-click in a session will work, but any subsequent commands (even the exact same code snippet) will fail and Cody will claim that no code was provided. 

https://github.com/sourcegraph/jetbrains/assets/113058716/143974a6-a5ba-4072-8060-9e97c2c55ee6

@mkondratek @taylorsperry

**Comment by mkondratek** [comment]
This one is fixed to some point by https://github.com/sourcegraph/jetbrains/pull/220 and eventually by https://github.com/sourcegraph/cody/pull/2803 (and the related PR).

All we need to do now is update codyCommit so it includes https://github.com/sourcegraph/cody/pull/2821.

(cc: @pkukielka)

**Comment by mkondratek** [comment]
it's fixed now for sure 😅
